spring.application.name=TastyMap

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}


spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

google.maps.api.key=${MAPS_API_KEY}

server.port=${SERVER_PORT}

jwt.access-secret=${JWT_SECRET_ACCESS}
jwt.access-exp-ms=${JWT_EXP_MS_ACCESS}


jwt.refresh-secret=${JWT_SECRET_REFRESH}
jwt.refresh-exp-ms=${JWT_EXP_MS_REFRESH}


app.base-url=${APP_BASE_URL}

app.lockout-minutes=${LOCKOUT_MINUTES}


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.jackson.serialization.write-dates-as-timestamps=false
server.forward-headers-strategy=native

spring.jpa.properties.hibernate.search.backend.directory.type=local-heap

spring.jpa.properties.hibernate.search.backend.directory.root=./lucene/indexes
spring.jpa.properties.hibernate.search.schema_management.strategy=create-or-validate

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=rag-restaurant-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Spring AI - Ollama Yap?land?rmas? (Gemma & Nomic)
spring.ai.ollama.base-url=${OLLAMA_BASE_URL}
spring.ai.ollama.chat.options.model=gemma:3b
spring.ai.ollama.embedding.options.model=nomic-embed-text

# Spring AI - Qdrant Vector DB Yap?land?rmas?
spring.ai.vectorstore.qdrant.host=${QDRANT_HOST}
spring.ai.vectorstore.qdrant.port=${QDRANT_PORT}
spring.ai.vectorstore.qdrant.collection-name=restaurants

LOCKOUT_MINUTES=15